<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findByPost($post)
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin("c.post", "p")
            ->where('p = :post')
            ->andWhere('c.parent is null')
            ->orderBy("c.createdAt", "ASC")
            ->setParameter('post', $post)
            ->getQuery();

        return $qb->getResult();
    }
}
