<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findByPost($post)
    {
        $qb = $this->createQueryBuilder('comment')
            ->where('comment.post = :post')
            ->andWhere('comment.parent is null')
            ->orderBy("comment.createdAt", "ASC")
            ->setParameter('post', $post)
            ->getQuery();

        return $qb->getResult();
    }
}
