# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    mail.service:
        class: AppBundle\Service\MailService
        arguments: ['@mailer', '%mailer_default_from%']