services:
    upload.annotation_reader:
        class: Ugho\UploadBundle\Reader\UploadAnnotationReader
        arguments: ["@annotations.reader"]

    upload.handler:
        class: Ugho\UploadBundle\Handler\UploadHandler
        arguments: ["%kernel.root_dir%"]

    upload.subscriber:
        class: Ugho\UploadBundle\Listener\UploadSubscriber
        arguments: ["@upload.annotation_reader", "@upload.handler"]
        tags:
            - { name: doctrine.event_subscriber }


